#===================================================================================#
# Site Information
#===================================================================================#
site_name: Cyber-Syntax Personal Notes
repo_name: Cyber-Syntax/learning-notes
repo_url: https://github.com/Cyber-Syntax/learning-notes
site_url: https://https://cyber-syntax.github.io/learning-notes
site_description: Cyber-Syntax Personal Notes
site_author: Cyber-Syntax
copyright: Copyright &copy; 2026 Cyber-Syntax.
edit_uri: edit/main/docs/

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
    name: material
    # custom_dir: overrides
    language: en
    font: false
    icon:
        # https://www.materialpalette.com/icons
        logo: simple/knowledgebase
    favicon: assets/images/pp.jpg
    features:
        - content.action.edit
        - content.action.view
        - content.code.copy
        - content.code.select
        - content.code.annotate
    include_sidebar: true
    palette:
        # https://www.materialpalette.com/colors
        - primary: indigo
        - scheme: slate
          #primary: "teal" # comment to replace by /docs/assets/stylesheets
          accent: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          #primary: "teal" # comment to replace by /docs/assets/stylesheets
          accent: teal
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji ""
          emoji_generator: !!python/name:material.extensions.emoji.to_svg ""
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format ""
plugins:
    - git-revision-date-localized:
          enable_creation_date: true
          type: datetime
          fallback_to_build_date: true
    - git-committers:
          repository: Cyber-Syntax/learning-notes
          branch: main
    - git-authors

extra_css:
    - assets/stylesheets/extra.css

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
# nav:
#     - Home:
#           - Home: "index.md"
#           - Projects: "portfolio/projects.md"
#           - Education: "portfolio/education.md"
#           - Dev: "dev/index.md"
